# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import pongps_pb2 as pongps__pb2


class GameServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.connectClient = channel.unary_unary(
                '/main.GameService/connectClient',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pongps__pb2.clientId.FromString,
                )
        self.updateClientPos = channel.unary_unary(
                '/main.GameService/updateClientPos',
                request_serializer=pongps__pb2.updatePaddlePos.SerializeToString,
                response_deserializer=pongps__pb2.currGameState.FromString,
                )
        self.clientScored = channel.unary_unary(
                '/main.GameService/clientScored',
                request_serializer=pongps__pb2.scored.SerializeToString,
                response_deserializer=pongps__pb2.replyScored.FromString,
                )
        self.ballmoved = channel.unary_stream(
                '/main.GameService/ballmoved',
                request_serializer=pongps__pb2.ballPosition.SerializeToString,
                response_deserializer=pongps__pb2.ballPosition.FromString,
                )
        self.StreamBallPosition = channel.unary_stream(
                '/main.GameService/StreamBallPosition',
                request_serializer=pongps__pb2.StreamBallPositionRequest.SerializeToString,
                response_deserializer=pongps__pb2.ballPosition.FromString,
                )


class GameServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def connectClient(self, request, context):
        """connect function
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateClientPos(self, request, context):
        """client sends to server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def clientScored(self, request, context):
        """server sends to client that one has scored
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ballmoved(self, request, context):
        """server send to client unsoliceted ball position (if the clients didnt move but the ball did)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamBallPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'connectClient': grpc.unary_unary_rpc_method_handler(
                    servicer.connectClient,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pongps__pb2.clientId.SerializeToString,
            ),
            'updateClientPos': grpc.unary_unary_rpc_method_handler(
                    servicer.updateClientPos,
                    request_deserializer=pongps__pb2.updatePaddlePos.FromString,
                    response_serializer=pongps__pb2.currGameState.SerializeToString,
            ),
            'clientScored': grpc.unary_unary_rpc_method_handler(
                    servicer.clientScored,
                    request_deserializer=pongps__pb2.scored.FromString,
                    response_serializer=pongps__pb2.replyScored.SerializeToString,
            ),
            'ballmoved': grpc.unary_stream_rpc_method_handler(
                    servicer.ballmoved,
                    request_deserializer=pongps__pb2.ballPosition.FromString,
                    response_serializer=pongps__pb2.ballPosition.SerializeToString,
            ),
            'StreamBallPosition': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamBallPosition,
                    request_deserializer=pongps__pb2.StreamBallPositionRequest.FromString,
                    response_serializer=pongps__pb2.ballPosition.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'main.GameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GameService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def connectClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.GameService/connectClient',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pongps__pb2.clientId.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updateClientPos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.GameService/updateClientPos',
            pongps__pb2.updatePaddlePos.SerializeToString,
            pongps__pb2.currGameState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def clientScored(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.GameService/clientScored',
            pongps__pb2.scored.SerializeToString,
            pongps__pb2.replyScored.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ballmoved(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/main.GameService/ballmoved',
            pongps__pb2.ballPosition.SerializeToString,
            pongps__pb2.ballPosition.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamBallPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/main.GameService/StreamBallPosition',
            pongps__pb2.StreamBallPositionRequest.SerializeToString,
            pongps__pb2.ballPosition.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
