# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pongps.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpongps.proto\x12\x04main\x1a\x1bgoogle/protobuf/empty.proto\"\x1a\n\x08\x63lientId\x12\x0e\n\x06whoami\x18\x01 \x01(\x05\"*\n\x0fupdatePaddlePos\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03pos\x18\x02 \x01(\x05\"i\n\rcurrGameState\x12\x0c\n\x04pos1\x18\x01 \x01(\x05\x12\x0c\n\x04pos2\x18\x02 \x01(\x05\x12\r\n\x05\x62\x61llx\x18\x03 \x01(\x05\x12\r\n\x05\x62\x61lly\x18\x04 \x01(\x05\x12\x0e\n\x06\x62\x61llVx\x18\x05 \x01(\x05\x12\x0e\n\x06\x62\x61llVy\x18\x06 \x01(\x05\"*\n\x06scored\x12\x0f\n\x07p1Score\x18\x01 \x01(\x05\x12\x0f\n\x07p2Score\x18\x02 \x01(\x05\"@\n\x0breplyScored\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t\x12$\n\x05reset\x18\x02 \x01(\x0b\x32\x15.main.updatePaddlePos2\xf0\x01\n\x0bGameService\x12\x37\n\rconnectClient\x12\x16.google.protobuf.Empty\x1a\x0e.main.clientId\x12=\n\x0fupdateClientPos\x12\x15.main.updatePaddlePos\x1a\x13.main.currGameState\x12/\n\x0c\x63lientScored\x12\x0c.main.scored\x1a\x11.main.replyScored\x12\x38\n\tballmoved\x12\x13.main.currGameState\x1a\x16.google.protobuf.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pongps_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTID._serialized_start=51
  _CLIENTID._serialized_end=77
  _UPDATEPADDLEPOS._serialized_start=79
  _UPDATEPADDLEPOS._serialized_end=121
  _CURRGAMESTATE._serialized_start=123
  _CURRGAMESTATE._serialized_end=228
  _SCORED._serialized_start=230
  _SCORED._serialized_end=272
  _REPLYSCORED._serialized_start=274
  _REPLYSCORED._serialized_end=338
  _GAMESERVICE._serialized_start=341
  _GAMESERVICE._serialized_end=581
# @@protoc_insertion_point(module_scope)
